<a href="https://colab.research.google.com/github/kushalgona/AI-Amrita/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
myPythonList = [1,9,8,3]
print(myPythonList)

[1, 9, 8, 3]


In [ ]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([1, 9, 8, 3])

In [ ]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [ ]:
x=numpy_array_from_list + 10
print(x)

[11 19 18 13]


In [ ]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)


(3,)
int32


In [ ]:
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [ ]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
d = np.array([[[1, 2,3],[4, 5, 6]],[[7, 8,9],[10, 11, 12]]])
print(d.shape)
(2, 2, 3)

(2, 2, 3)


(2, 2, 3)

In [ ]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [ ]:
import numpy as np
np.ones((1,2,3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [ ]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [ ]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [ ]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.09428802 4.02319501 3.99024926 4.27195676 4.95471312 4.93397138
 5.10241076 5.08759851 5.15255162 4.60171479]


In [ ]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2  #immutable
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [ ]:
np.arange(1, 11)	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [ ]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [ ]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

In [ ]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [ ]:
print('Second column:', e[:,1])	

Second column: [2 5]


In [ ]:
print(e[1, :2])

[4 5]


In [ ]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[3.95788309 5.05972603 4.82248317 4.89765649 5.24265247 3.75256129
 5.50175557 4.75772891 5.02266628 4.87312536]


In [ ]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

3.7525612852766956
5.501755574975822
4.788823865372761
4.885390925147945
0.5126066822668953


In [ ]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [ ]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [ ]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [ ]:
# Let's create a square matrix (NxN matrix)
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

In [ ]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -3.18863232e-15 -1.34840081e-16] [[-0.15115432  0.72704996  0.50370019 -0.06456091]
 [-0.34923733  0.28320876 -0.8319577  -0.31932112]
 [-0.54732033 -0.16063243  0.15281481  0.83232496]
 [-0.74540333 -0.60447363  0.17544269 -0.44844294]]


In [ ]:
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [ ]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans) 

[[ 4 12]
 [ 1  3]]


In [ ]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]
